cgarwood/homeassistant-fullykiosk

custom_components/fullykiosk/binary_sensor.py, custom_components/fullykiosk/light.py, custom_components/fullykiosk/media_player.py, custom_components/fullykiosk/switch.py
PlatformDevice -> PlatformEntity for compatibility with newer HA versions.
=> Update deprecated class names

.devcontainer/configuration.yaml, .devcontainer/devcontainer.json, .vscode/tasks.json
Add devcontainer based on https://github.com/custom-components/blueprint
=> Add devcontainer

README.md, custom_components/fullykiosk/binary_sensor.py, custom_components/fullykiosk/light.py, custom_components/fullykiosk/media_player.py, custom_components/fullykiosk/sensor.py, custom_components/fullykiosk/switch.py
Clean up unused imports, add docstrings, other general cleanup
=> Code cleanup

custom_components/fullykiosk/config_flow.py
=> Update config flow schema, set default port

custom_components/fullykiosk/manifest.json, custom_components/fullykiosk/switch.py
Adds switches for Kiosk Lock and Maintenance Mode
Requests state refresh after turn_on and turn_off events to fix switch state flapping in the UI
=> Add new switch types & better state refresh

custom_components/fullykiosk/light.py
Refreshes the state after issuing a turn on or turn off command
Fixes #4
=> Fix state refresh for light entity (screen on/off)

custom_components/fullykiosk/const.py, custom_components/fullykiosk/manifest.json, custom_components/fullykiosk/media_player.py, custom_components/fullykiosk/services.yaml
Implements several services on the `media_player` entity, contributes to #13 
(note, some existing imports were reordered because I enabled pre-commit, but couldn't get that to pass)
=> Add services

custom_components/fullykiosk/config_flow.py
cc @bjw-s 
Fix config flow after upstream lib was migrated to aiohttp
fixes #24
=> Fix config flow

custom_components/fullykiosk/config_flow.py
😅 this is what I get for not actually testing the fix the first time...
=> Actually fix config flow

custom_components/fullykiosk/sensor.py
Adds 4 new sensors:
Internal Storage free/total
RAM free/total
Fixes #36
=> Add sensors for internal storage and RAM use

custom_components/fullykiosk/services.yaml
Add selectors to services.yaml to support the new call service UI.
=> Add selectors for service parameters

custom_components/fullykiosk/config_flow.py, custom_components/fullykiosk/coordinator.py
To help with older/slower devices
=> Increase timeout to 15 seconds

custom_components/fullykiosk/binary_sensor.py, custom_components/fullykiosk/light.py, custom_components/fullykiosk/media_player.py, custom_components/fullykiosk/sensor.py, custom_components/fullykiosk/switch.py
=> Device configuration url

custom_components/fullykiosk/sensor.py
To follow updated HA best practices...
=> Refactor sensors to use SensorEntityDescription and shorthand attributes

custom_components/fullykiosk/binary_sensor.py
To follow updated HA best-practices
=> Refactor binary_sensor to use entity descriptions

custom_components/fullykiosk/__init__.py, custom_components/fullykiosk/number.py
Adds the number platform with entities for screensaver time and brightness, as well as screen off time.
=> Add number platform

custom_components/fullykiosk/media_player.py
Fixes the TTS media URL in HA 2022.5
=> Fix TTS Media URL

custom_components/fullykiosk/sensor.py
=> Fix last app start timestamp

custom_components/fullykiosk/media_player.py
=> Loosen validation for load_url service from cv.url->cv.string

custom_components/fullykiosk/number.py
=> Fix deprecation warning in HA 2022.7
